Соединяемся с базой, если указать имя файла как `:memory:`, база будет создана в оперативной памяти.

    You can also supply the special name :memory: to create a database in RAM.

In [ ]:
import sqlite3
conn = sqlite3.connect('netflix.sqlite')

<a href="https://docs.python.org/3/library/sqlite3.html">Документация</a>

In [ ]:
c = conn.cursor() # Стандартный курсор = итератор по результатам запросов.

In [ ]:
for row in c.execute("SELECT * FROM netflix_titles limit 3"):
    print(row)

(81145628, 'Movie', 'Norm of the North: King Sized Adventure', 'Richard Finn, Tim Maltby', 'Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson', 'United States, India, South Korea, China', 'September 9, 2019', 2019, 'TV-PG', '90 min', 'Children & Family Movies, Comedies', 'Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.')
(80117401, 'Movie', 'Jandino: Whatever it Takes', '', 'Jandino Asporaat', 'United Kingdom', 'September 9, 2016', 2016, 'TV-MA', '94 min', 'Stand-Up Comedy', 'Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of "Sex on Fire" in his comedy show.')
(70234439, 'TV Show', 'Transformers Prime', '', 'Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle', 'United States', 'September 8, 2018', 2013, 'TV-Y7-FV', '1 Season', "Kids' TV", 'With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron.')

Можно еще получать по одному:

In [ ]:
c.execute("SELECT * FROM netflix_titles limit 3")

In [ ]:
c.fetchone()

(81145628,
 'Movie',
 'Norm of the North: King Sized Adventure',
 'Richard Finn, Tim Maltby',
 'Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson',
 'United States, India, South Korea, China',
 'September 9, 2019',
 2019,
 'TV-PG',
 '90 min',
 'Children & Family Movies, Comedies',
 'Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.')

In [ ]:
c.fetchone()

(80117401,
 'Movie',
 'Jandino: Whatever it Takes',
 '',
 'Jandino Asporaat',
 'United Kingdom',
 'September 9, 2016',
 2016,
 'TV-MA',
 '94 min',
 'Stand-Up Comedy',
 'Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of "Sex on Fire" in his comedy show.')

In [ ]:
c.fetchone()

(70234439,
 'TV Show',
 'Transformers Prime',
 '',
 'Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle',
 'United States',
 'September 8, 2018',
 2013,
 'TV-Y7-FV',
 '1 Season',
 "Kids' TV",
 'With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron.')

In [ ]:
c.fetchone() # Все, курсор закончился.

In [ ]:
c.execute("SELECT * FROM netflix_titles limit 3")
c.fetchall() # Как видим, у нас не итератор, а полноценный список.

[(81145628,
  'Movie',
  'Norm of the North: King Sized Adventure',
  'Richard Finn, Tim Maltby',
  'Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson',
  'United States, India, South Korea, China',
  'September 9, 2019',
  2019,
  'TV-PG',
  '90 min',
  'Children & Family Movies, Comedies',
  'Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.'),
 (80117401,
  'Movie',
  'Jandino: Whatever it Takes',
  '',
  'Jandino Asporaat',
  'United Kingdom',
  'September 9, 2016',
  2016,
  'TV-MA',
  '94 min',
  'Stand-Up Comedy',
  'Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of "Sex on Fire" in his comedy show.'),
 (70234439,
  'TV Show',
  'Transformers Prime',
  '',
  'Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle',
  'United States',
  'September 8, 2018',
  2013,
  'TV-Y7-FV',
  '1 Season',
  "Kids' TV",
  'With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron.')]

Как видим, не очень удобно, что возвращаются кортежи. Удобней было бы, чтобы словари.

In [ ]:
c.description # вот тут есть описания полей.

(('show_id', None, None, None, None, None, None),
 ('type', None, None, None, None, None, None),
 ('title', None, None, None, None, None, None),
 ('director', None, None, None, None, None, None),
 ('cast', None, None, None, None, None, None),
 ('country', None, None, None, None, None, None),
 ('date_added', None, None, None, None, None, None),
 ('release_year', None, None, None, None, None, None),
 ('rating', None, None, None, None, None, None),
 ('duration', None, None, None, None, None, None),
 ('listed_in', None, None, None, None, None, None),
 ('description', None, None, None, None, None, None))

In [ ]:
def dict_factory(cursor, row):
    # обертка для преобразования
    # полученной строки. (взята из документации)
    d = {}
    for idx, col in enumerate(cursor.description):
        d[col[0]] = row[idx]
    return d

In [ ]:
conn.row_factory = dict_factory

In [ ]:
с = conn.cursor()
c.execute("SELECT * FROM netflix_titles limit 3")
c.fetchall() # Теперь буду словари

[(81145628,
  'Movie',
  'Norm of the North: King Sized Adventure',
  'Richard Finn, Tim Maltby',
  'Alan Marriott, Andrew Toth, Brian Dobson, Cole Howard, Jennifer Cameron, Jonathan Holmes, Lee Tockar, Lisa Durupt, Maya Kay, Michael Dobson',
  'United States, India, South Korea, China',
  'September 9, 2019',
  2019,
  'TV-PG',
  '90 min',
  'Children & Family Movies, Comedies',
  'Before planning an awesome wedding for his grandfather, a polar bear king must take back a stolen artifact from an evil archaeologist first.'),
 (80117401,
  'Movie',
  'Jandino: Whatever it Takes',
  '',
  'Jandino Asporaat',
  'United Kingdom',
  'September 9, 2016',
  2016,
  'TV-MA',
  '94 min',
  'Stand-Up Comedy',
  'Jandino Asporaat riffs on the challenges of raising kids and serenades the audience with a rousing rendition of "Sex on Fire" in his comedy show.'),
 (70234439,
  'TV Show',
  'Transformers Prime',
  '',
  'Peter Cullen, Sumalee Montano, Frank Welker, Jeffrey Combs, Kevin Michael Richardson, Tania Gunadi, Josh Keaton, Steve Blum, Andy Pessoa, Ernie Hudson, Daran Norris, Will Friedle',
  'United States',
  'September 8, 2018',
  2013,
  'TV-Y7-FV',
  '1 Season',
  "Kids' TV",
  'With the help of three human allies, the Autobots once again protect Earth from the onslaught of the Decepticons and their leader, Megatron.')]

In [ ]:
c.execute("SELECT count(*) as cnt FROM netflix_titles where listed_in='Stand-Up Comedy'")
c.fetchall() # Сколько вообще стендап комедий

[(273,)]

In [ ]:
c.execute("SELECT rating, count(*) as cnt FROM netflix_titles group by rating")
c.fetchall() # Группируем по рейтингу
# Важно тут сказать, что SQL -- замена pandas полноценная,
# и всю обработку данных можно делать прямо внутри него

[('', 10),
 ('G', 37),
 ('NC-17', 2),
 ('NR', 218),
 ('PG', 184),
 ('PG-13', 286),
 ('R', 508),
 ('TV-14', 1698),
 ('TV-G', 149),
 ('TV-MA', 2027),
 ('TV-PG', 701),
 ('TV-Y', 143),
 ('TV-Y7', 169),
 ('TV-Y7-FV', 95),
 ('UR', 7)]

# Задания

1. Нормализовать базу данных относительно актеров. Выделить таблицу с актерами, а также таблицу многие-ко-многим `актер-фильм`

2. Исходя из этой таблицы, средствами SQL, вычислить наболее часто работающую друг с другом пару актеров.

In [ ]:
connection = sqlite3.connect('task1.sqlite')
cursor = connection.cursor()
cursor.execute('''CREATE TABLE actors (
                id INTEGER PRIMARY KEY,
                name TEXT )
''')

cursor.execute('''CREATE TABLE movies (
                id INTEGER PRIMARY KEY,
                title TEXT )
''')

cursor.execute('''CREATE TABLE actor_movie (
               actor_id INTEGER,
               movie_id INTEGER,
               FOREIGN KEY (actor_id) REFERENCES actors(id),
               FOREIGN KEY (movie_id) REFERENCES movies(id) )
''')

connection.commit()
connection.close()

In [ ]:
connectionNetflix = sqlite3.connect('netflix.sqlite')
cursorNetflix = connectionNetflix.cursor()
cursorNetflix.execute('select title, "cast" from netflix_titles')
data = cursorNetflix.fetchall()
connectionNetflix.close()

import re
updateData = []
uniqueActors = set()
for i in data:
    film, actors = i
    cast = re.split(r' ,|, |,', actors)
    uniqueActors = uniqueActors.union(set(cast))
    updateData.append((film, cast))

In [ ]:
connectionActors = sqlite3.connect('task1.sqlite')
cursorActors = connectionActors.cursor()
for actor in uniqueActors:
    cursorActors.execute("INSERT INTO actors VALUES (NULL, ?)", (actor,))
connectionActors.commit()
connectionActors.close()

In [ ]:
connectionFilms = sqlite3.connect('task1.sqlite')
cursorMovies = connectionFilms.cursor()
for i in updateData:
    film, actors = i
    cursorMovies.execute("INSERT INTO movies VALUES (NULL, ?)", (film,))
connectionFilms.commit()
connectionFilms.close()

In [ ]:
connectionActorFilm = sqlite3.connect('task1.sqlite')
cursorActors = connectionActorFilm.cursor()
cursorFilms = connectionActorFilm.cursor()
cursorActorFilm = connectionActorFilm.cursor()
for i in updateData:
    film, actors = i
    cursorActorFilm.execute('SELECT id FROM movies WHERE title = ?', (film,))
    uniqueFilm = cursorActorFilm.fetchone()
    for actor in actors:
        cursorActors.execute('SELECT id FROM actors WHERE name = ?', (actor,))
        uniqueActor = cursorActors.fetchone()
        cursorActorFilm.execute("INSERT INTO actor_movie (actor_id, movie_id) VALUES (?, ?)", (uniqueActor[0], uniqueFilm[0]))
connectionActorFilm.commit()
connectionActorFilm.close()

In [27]:
connectionFindActors = sqlite3.connect('task1.sqlite')
cursorFindActors = connectionFindActors.cursor()
cursorFindActors.execute('''
    SELECT a1.name AS actor1_name, a2.name AS actor2_name, COUNT(*) AS movies_together
    FROM actor_movie am1
    JOIN actor_movie am2 ON am1.movie_id = am2.movie_id AND am1.actor_id < am2.actor_id
    JOIN actors a1 ON am1.actor_id = a1.id
    JOIN actors a2 ON am2.actor_id = a2.id
    GROUP BY actor1_name, actor2_name
    ORDER BY movies_together DESC
    LIMIT 1
''')
actors = cursorFindActors.fetchone()
print(actors[0])
print(actors[1])
connectionFindActors.close()

John Paul Tremblay
Robb Wells